services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: diffusion_app:latest
    container_name: diffusion_app
    stdin_open: true
    tty: true
    volumes:
      - ./data:/diffusion/data
      - ./.env:/diffusion/.env
